_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 6
DATASETS:
  TRAIN: ("voc_2007_train",)
  TEST:  ("voc_2007_val",)
SOLVER:
  STEPS: (35000, 42000)
  MAX_ITER: 45000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
